name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt' # Options: adopt, zulu, temurin, etc.

    - name: Verify Java version
      run: java -version
        
    - run: ./gradlew build --no-daemon --stacktrace




