name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - run: ls /Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home

        
    - run: ./gradlew build --no-daemon




      

   

   
