name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt' # Options: adopt, zulu, temurin, etc.

    - name: Verify Java version
      run: java -version

    - name: clean the previous build file    
      run: ./gradlew clean

    - name: stop    
      run: ./gradlew --stop

    - name: start the fresh new build
      run: ./gradlew build --refresh-dependencies

      




